### By - Yash Mathur 
###### Stage 2 Quiz.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
df=pd.read_csv('energydata_complete.csv')
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,55.20,7.026667,84.256667,17.200000,41.626667,18.2,48.900000,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,55.20,6.833333,84.063333,17.200000,41.560000,18.2,48.863333,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,55.09,6.560000,83.156667,17.200000,41.433333,18.2,48.730000,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,55.09,6.433333,83.423333,17.133333,41.290000,18.1,48.590000,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,55.09,6.366667,84.893333,17.200000,41.230000,18.1,48.590000,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [5]:
df=df.drop(['date','lights'],axis=1)

In [6]:
columns=df.columns

In [7]:
df=pd.DataFrame(scaler.fit_transform(df))
df.columns=columns
df

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,0.381070,0.841827,0.170594,0.653428,0.173329,0.661412,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,0.375443,0.839872,0.170594,0.651064,0.173329,0.660155,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,0.367487,0.830704,0.170594,0.646572,0.173329,0.655586,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,0.363800,0.833401,0.164310,0.641489,0.164175,0.650788,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,0.361859,0.848264,0.170594,0.639362,0.164175,0.650788,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.084112,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,0.339590,0.898317,0.000000,0.858624,0.755319,0.768386,0.701645,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.074766,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,0.338487,0.880852,0.000000,0.864010,0.752280,0.768386,0.691912,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.242991,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,0.337585,0.864260,0.000000,0.862394,0.751773,0.768386,0.687457,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.383178,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,0.336583,0.829525,0.000000,0.858624,0.748075,0.764953,0.682617,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.392523,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,0.336583,0.788580,0.000000,0.858624,0.739504,0.771681,0.690062,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [8]:
x_12=df[['T2']].values
y_12=df['T6'].values

In [9]:
from sklearn.model_selection import train_test_split
x_12_train,x_12_test,y_12_train,y_12_test=train_test_split(x_12,y_12,random_state=42,test_size=0.3)

In [10]:
from sklearn.linear_model import LinearRegression
regressor_12=LinearRegression()
regressor_12.fit(x_12_train,y_12_train)

LinearRegression()

In [11]:
y_pred_12=regressor_12.predict(x_12_test)

In [13]:
from sklearn.metrics import r2_score
r2=r2_score(y_12_test,y_pred_12)
np.round(r2,2)

0.64

##### 0.64 R^2 score

In [14]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_12_test,y_pred_12)
np.round(mse,2)

0.01

##### 0.01 mse

In [15]:
rss=np.sum(np.square(y_12_test-y_pred_12))
np.round(rss,2)

66.12

##### 66.12 rss

In [17]:
from sklearn.metrics import mean_squared_error
rmse=np.sqrt(mean_squared_error(y_12_test,y_pred_12))
np.round(rmse,3)

0.106

##### 0.106 rmse

In [18]:
target=df['Appliances']

In [19]:
features=['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'rv1', 'rv2']

In [20]:
x=df.drop(['Appliances'],axis=1).values
y=df['Appliances'].values

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_Test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [23]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()
linear.fit(x_train,y_train)

LinearRegression()

In [24]:
importance=pd.DataFrame({'Feature':features,'Imp':linear.coef_})
importance=importance.sort_values('Imp',ascending=False)
importance

        Feature       Imp
1          RH_1  0.553547
4            T3  0.290627
10           T6  0.236425
23    Tdewpoint  0.117758
14           T8  0.101995
5          RH_3  0.096048
11         RH_6  0.038049
21    Windspeed  0.029183
6            T4  0.028981
7          RH_4  0.026386
9          RH_5  0.016006
22   Visibility  0.012307
12           T7  0.010319
19  Press_mm_hg  0.006839
25          rv2  0.000770
24          rv1  0.000770
0            T1 -0.003281
8            T5 -0.015657
17         RH_9 -0.039800
13         RH_7 -0.044614
20       RH_out -0.077671
15         RH_8 -0.157595
16           T9 -0.189941
2            T2 -0.236178
18        T_out -0.321860
3          RH_2 -0.456698

##### RH_1 highest and RH_2 lowest

In [26]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.001)
lasso.fit(x_train,y_train)
lasso.coef_

array([ 0.        ,  0.01787993,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
       -0.00011004, -0.        , -0.        ,  0.        , -0.        ,
       -0.04955749,  0.00291176,  0.        ,  0.        , -0.        ,
       -0.        ])

##### 4 have negative values.

In [27]:
y_lasso=lasso.predict(x_Test)
rmse_lasso=np.sqrt(mean_squared_error(y_test,y_lasso))
np.round(rmse_lasso,3)

0.094

##### 0.094 rmse lasso

### Thank You!!